# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"

HIST_STAMPS="%b-%d %H:%M"

plugins=(starship eza git)

source $ZSH/oh-my-zsh.sh

# User configuration

# aliases
alias alirg='alias | rg'

DISABLE_AUTO_UPDATE=true
DISABLE_UPDATE_PROMPT=true
